/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_nulstudio_medicalcommunication_controller_TestController */

#ifndef _Included_com_nulstudio_medicalcommunication_controller_TestController
#define _Included_com_nulstudio_medicalcommunication_controller_TestController
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_nulstudio_medicalcommunication_controller_TestController
 * Method:    testJni
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_nulstudio_medicalcommunication_controller_TestController_testJni
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
